### ISSUE TITLE
Ecological Society of America (ESA)

### ISSUE THREAD

**Issue by stefaniebutland** [NASA-Openscapes/workshop-planning#1]
## [Ecological Society of America (ESA)](https://www.esa.org/longbeach2024/)

- Attending - Bri, Rupesh, Mahsa, Michele
- Workshops: GEDI (Led by Mahsa), Openness (Bri +), Bioscapes (Michele)
- Location: Long Beach, CA, USA

### Important Dates:
- Workshop deadline: Dec. 15, 2023 
- Abstract Submissions Open: Jan 11, Deadline: Feb. 23
- Registration deadline: May 22
- Date of Event: Aug 4-9
- Date of pre-meeting workshop: Aug 3

**Comment by amfriesz** [comment]
We did not get enough people registered to hold the workshop, so we had to cancel. Our abstract was also denied for the session we submitted to. The LP DAAC will not be attending ESA this year.

**Comment by jules32** [comment]
That is a shame, thank you for sharing here. I will close this issue.
