### ISSUE TITLE
EMIT & ECOSTRESS Combined Science Team Meeting

### ISSUE THREAD

**Issue by BriannaLind** [NASA-Openscapes/workshop-planning#106]
This combined meeting would include the EMIT ROSES team, GHG team, Applications team, and Cal/Val team.
Our first choice is to use the von Karman auditorium at JPL which is free and can be configured outside the security perimeter.  Unfortunately, the dates we can access this auditorium are limited. While planned primarily in person, we would include a virtual option as well.

**Comment by ebolch** [comment]
This meeting will be hybrid.

October 1-3, 2024

Location:
Marriott Courtyard Old Town Pasadena
Pasadena, CA

**Comment by amfriesz** [comment]
Dates have changed to Sept 30 - Oct 2

**Comment by jules32** [comment]
Hi @amfriesz will you use the 2i2c Openscapes Hub for this and how can we help?

**Comment by mjami00** [comment]
Those meeting held without the combined workshop. We only had a short workshop session in ECOSTRESS meeting and did not use 2i2c.
