### ISSUE TITLE
ECOSTRESSS Science Team Technical Session Planning

### ISSUE THREAD

**Issue by amfriesz** [NASA-Openscapes/workshop-planning#123]
# ECOSTRESS Science Team Technical Session

## Session Details

**Location:**

**Date:** October 1, 2024

**Team:**
- Gregory Halverson (JPL)
- Madeleine Pascolini-Campbell (JPL)
- @mjami00 (LP DAAC)
- @amfriesz (LP DAAC)
- Cole Krehbiel (LP DAAC)

## Agenda

| Time | Topic | Lead/Instructor |
| --- | --- | --- |
| <ADD TIME> | <ADD TOPIC | <ADD LEAD> |
| <ADD TIME> | <ADD TOPIC | <ADD LEAD> |
| <ADD TIME> | <ADD TOPIC | <ADD LEAD> |

### Possible Topics
- Walk-through of available resources
- QGIS - Making maps with ECOSTRESS
- QGIS - Stream ECOSTRESS Tiled data ([EMIT example](https://github.com/nasa/EMIT-Data-Resources/blob/main/guides/Streaming_cloud_optimized_geotiffs_using_QGIS.md))
- `earthaccess` search and access(?) tutorial
- Setting up a Python env (mamba to Jupyter hero!)
- Python - How to work with ECOSTRESS data (swath, gridded, tiled?)
- Python - How to  ...

### Decisions

- [ ] Do we need the 2i2c JupyterHub?
- [ ] How to handle GitHub (suggest not combining 'working with data' tutorial session with 'how to use GitHub' session)
- [ ] Do we need to plan for a 'side' GitHub session? Prepared material or office hours style?
- [ ] When to meet next? How often to meet?

## Resources

- [ECOSTRESS tutorials](https://github.com/ECOSTRESS-Tutorials)
- https://github.com/nasa/ECOSTRESS-Data-Resources
- https://github.com/nasa/VITALS
- [`earthaccess` tutorial](https://github.com/CU-ESIIL/HYR-SENSE/blob/main/notebooks/how_to/earthaccess_Introduction.ipynb)
- [Working with ECOSTRESS](https://github.com/CU-ESIIL/HYR-SENSE/blob/main/notebooks/how_to/Work_with_ECOSTRESS.ipynb)

**Comment by mjami00** [comment]
If we decide to use 2i2c, we need to reach out to their team a month in advance

https://nasa-openscapes.github.io/earthdata-cloud-cookbook/policies-admin/leading-workshops.html#using-the-openscapes-2i2c-hub-in-a-workshop

**Comment by amfriesz** [comment]
Draft agenda: https://ecostress.jpl.nasa.gov/downloads/science_team_meetings/2024/DRAFT_AGENDA_OCTOBER_2024_23Aug2024_v1.pdf
