### ISSUE TITLE
SWOT-PODAAC workshop AGU Chapman - Feb 13, 2024

### ISSUE THREAD

**Issue by stefaniebutland** [NASA-Openscapes/workshop-planning#2]
SWOT-PODAAC workshop  at [AGU Chapman](https://www.google.com/search?client=firefox-b-1-e&q=agu+chapman+remote+sensing+water+2024): Remote Sensing and Water

Feb 13

mentors/co-leads/assists: Cassie Nickles, Catalina Taglialatela

**Comment by jules32** [comment]
Today Cassie, Bri, Stef, and I huddled to talk about SWOT workshop prep

- https://nasa-openscapes.github.io/earthdata-cloud-cookbook/leading-workshops/add-folks-to-2i2c-github-teams.html
- new Org and teams: https://github.com/orgs/nasa-openscapes-workshops/teams

Next steps: 
- [ ] Cassie email support@2i2c.freshdesk.com to tell 45 person workshop and date, reuse text from Bri
- [ ] Julie will create the other 2 teams and email support@2i2c.freshdesk.com
- [ ] Stef to review https://nasa-openscapes.github.io/earthdata-cloud-cookbook/leading-workshops/add-folks-to-2i2c-github-teams.html and add more screenshots and update links to `nasa-openscapes-workshops`
- [ ] Meet Feb 13 at 9am PT (morning of) to add folks to Hub. Calendar invite sent

**Comment by stefaniebutland** [comment]
Feb 13 we used [Kyber](https://openscapes.github.io/kyber/) to add GitHub usernames for workshop participants to GitHub Team https://github.com/orgs/nasa-openscapes-workshops/teams/workshopaccess-2i2c. Worked like a charm.

@cassienickles says the SWOT workshop was a great success!! No issues

**Comment by jules32** [comment]
Some feedback from Catalina 🎉 : https://github.com/NASA-Openscapes/workshop-planning/issues/58#issuecomment-1954935497
