### ISSUE TITLE
Year of Open Science Culminating Conference - Mar 21-22

### ISSUE THREAD

**Issue by BriannaLind** [NASA-Openscapes/workshop-planning#22]
VIRTUAL [link](https://www.cos.io/blog/year-of-open-science-culminating-conference#:~:text=Year%20of%20Open%20Science%20Culminating%20Conference%3A%20Shaping%20the%20Future%20of%20Open%20Research,-November%2016th%2C%202023&text=To%20culminate%20the%202023%20Year,March%2021%20and%2022%2C%202024.)

- Conference Submissions Open: January 9, 2024
- Conference Registration Opens: January 16, 2024 - https://www.cos.io/yos-conference
- Proposal Submission Deadline: January 24, 2024
- Notification of Acceptance: February 9, 2024
- Conference Date: March 21-22, 2024

**Comment by jules32** [comment]
I'd like to submit something like this, if anyone would be interested in copresenting!

> 2023 was the Year of Open Science. It was also the [Year of Taylor Swift](https://www.nytimes.com/2023/12/15/podcasts/the-daily/the-year-of-taylor-swift.html), according the The New York Times. What can the Open Science movement learn from Taylor Swift, whose specificity in her storytelling has connected and empowered millions of people? "Taylor Swift has taken her story and made it big enough for everybody". Here we'll share Open Science momentum and challenges we've seen in environmental and Earth science, with specific stories from NASA Openscapes.

**Comment by BriannaLind** [comment]
Submission was accepted!

We are scheduled for a 12-minute presentation on March 21 from 4-5pm EST

**Comment by jules32** [comment]
NASA Openscapes Session Accepted too!!

We are scheduled for 
March 22	9-10 am ET
Session L-C
Lightning - 10 minutes
