### ISSUE TITLE
Year of Open Science Proposal Submission Deadline

### ISSUE THREAD

**Issue by BriannaLind** [NASA-Openscapes/workshop-planning#23]
[submission form](https://docs.google.com/forms/d/e/1FAIpQLSeOssqDx0N-oNGi-fRE5OaQ-wnJKz2Ao9hOtuWDJVxFpvZp9A/viewform)

**Comment by jules32** [comment]
I'd like to submit something like this, if anyone would be interested in copresenting!

> 2023 was the Year of Open Science. It was also the [Year of Taylor Swift](https://www.nytimes.com/2023/12/15/podcasts/the-daily/the-year-of-taylor-swift.html), according the The New York Times. What can the Open Science movement learn from Taylor Swift, whose specificity in her storytelling has connected and empowered millions of people? "Taylor Swift has taken her story and made it big enough for everybody". Here we'll share Open Science momentum and challenges we've seen in environmental and Earth science, with specific stories from NASA Openscapes.

**Comment by BriannaLind** [comment]
@jules32 I think thats a great idea! I can support - but probably not co-present bc LP and EMIT are going to do one together :)

**Comment by jules32** [comment]
Submitted! @BriannaLind when you're done submitting, would you like to close this issue? It's so satisfying :)

**Comment by BriannaLind** [comment]
Sweet!  I just finished submitting too :)

**Comment by BriannaLind** [comment]
:)
