### ISSUE TITLE
Summer ESIP July 22-26. May 10 call for sessions

### ISSUE THREAD

**Issue by BriannaLind** [NASA-Openscapes/workshop-planning#30]
Asheville, NC

**Comment by jules32** [comment]
**Call for Sessions and Registration is Open**
Grounded in Trust: Data Ethics Empower Collaboration 

We continue to explore this theme in the 2024 July ESIP Meeting — and we look forward to seeing where your ideas take us! Join us in Asheville, North Carolina, or virtually from July 22-26.


Key Deadlines 

All meeting dates are now listed on our new [ESIP Community Calendar](https://esipfed.us2.list-manage.com/track/click?u=ca50850794ee72b04765ac93c&id=3eb6b8f3f6&e=b91f4a549c), too.

    May 1 - [Open Office Hour](https://esipfed.us2.list-manage.com/track/click?u=ca50850794ee72b04765ac93c&id=df2ddd607e&e=b91f4a549c) for session organizers

    May 10 - [Call for Sessions](https://esipfed.us2.list-manage.com/track/click?u=ca50850794ee72b04765ac93c&id=2be9b593b9&e=b91f4a549c) closes

    June 12 - [Session Design Workshop](https://esipfed.us2.list-manage.com/track/click?u=ca50850794ee72b04765ac93c&id=19c5338d03&e=b91f4a549c) for session organizers

    June 22 - [Early Registration](https://esipfed.us2.list-manage.com/track/click?u=ca50850794ee72b04765ac93c&id=84f67558ef&e=b91f4a549c) ends

    June 22 - [Registration assistance forms](https://esipfed.us2.list-manage.com/track/click?u=ca50850794ee72b04765ac93c&id=c7ccbb247e&e=b91f4a549c) due

    June 22 - [Hotel room block](https://esipfed.us2.list-manage.com/track/click?u=ca50850794ee72b04765ac93c&id=b485665b9a&e=b91f4a549c) closes (may fill up before that!)

    July 22-26 - [ESIP Meeting](https://esipfed.us2.list-manage.com/track/click?u=ca50850794ee72b04765ac93c&id=626e45577e&e=b91f4a549c) - Asheville, NC and virtual

**Comment by jules32** [comment]
Submitted a NASA Openscapes session https://github.com/NASA-Openscapes/how_we_work/issues/61
