### ISSUE TITLE
AGU 2024 abstract deadline - July 31

### ISSUE THREAD

**Issue by BriannaLind** [NASA-Openscapes/workshop-planning#33]
## Potential sessions to submit abstracts to
please add others and share where you're submitting!

[GC021 - Advancing Global Imaging Spectroscopy and Thermal Infrared Measurements, including results from ECOSTRESS, EMIT, SBG and others](https://agu.confex.com/agu/agu24/prelim.cgi/Session/2291280) - hosted by JPL folks

[ED034 - Reflections on Open Science: Sharing Stories, Progress, and Lessons Learned](https://agu.confex.com/agu/agu24/prelim.cgi/Session/228837) (Lucas Sterzinger)

[N022 - Earth Science data and the cloud: Past, present and future](https://agu.confex.com/agu/agu24/prelim.cgi/Session/224517) - Doug Newman 

[IN048 - Transforming Earth Science Data](https://agu.confex.com/agu/agu24/prelim.cgi/Session/224697) - NASA Openscapes (Michele Thornton, Vinnie, James Gallagher, Owen Littlejohns)

[U001: Accelerating Scientific Discovery and Interdisciplinary Collaboration through Cloud Computing Hubs and Tools](https://agu.confex.com/agu/agu24/prelim.cgi/Session/225615) (A Barrett rec) Tasha Snow & Jessica Scheik
 
[IN053](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fagu.confex.com%2Fagu%2Fagu24%2Fprelim.cgi%2FSession%2F229151&data=05%7C02%7Cian.t.carroll%40nasa.gov%7C652c49bfd5fe478f939d08dc9f31601d%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638560281633037714%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=S9N1yTIXn0i9yj6HM6kJT6F8TdYx6UkvawLvj2ct608%3D&reserved=0) - Open To Celebrate!: Open Science Success Stories in Heliophysics and the Geosciences (Rebecca Ringuette, Christopher Bard, Caroline Coward)

“[IN026 Flourishing Science Commons: Data Science, Open Science, and Knowledge Communities](https://agu.confex.com/agu/agu24/prelim.cgi/Session/227862)” - [Ryan McGranaghan](http://www.ryanmcgranaghan.com/) (NASA Jet Propulsion Laboratory (JPL)) on behalf of [Lisa Cuevas-Shaw](https://www.cos.io/team/lisa-cuevas-shaw) (Center for Open Science) [Chelle Gentemann](http://www.faralloninstitute.org/chelle) 
[Elle O’Brien](https://elle-obrien.com/) (University of Michigan) 

[IN032 - Maximizing Earth Observation Impact: Advancing Multi-Mission Solutions](https://agu.confex.com/agu/agu24/prelim.cgi/Session/228037) - Brianna Pagán (GES DISC) is an invited speaker

## Google Doc for Abstracts
If you’re submitting an abstract to AGU, please develop/paste it in here so we’re all aware/can contribute/reuse what we’re all doing!

https://docs.google.com/document/d/1RbuVA66X4Rl9MQhfYhZJh-RFFTM9uYGxtrox7KDwi8o/edit?usp=sharing

**Comment by danielfromearth** [comment]
Looks like I'll be submitting an abstract to [IN048 - Transforming Earth Science Data](https://agu.confex.com/agu/agu24/prelim.cgi/Session/224697) about chaining together data transformation services in Harmony (for the TEMPO mission).

**Comment by jules32** [comment]
@danielfromearth - awesome! And I think it's great to share like you did in this issue for our awareness, and then you can share the abstract/ more details in the doc!

**Comment by ScienceCat18** [comment]
Hey all - I drafted an abstract for the [U001: Accelerating Scientific Discovery and Interdisciplinary Collaboration through Cloud Computing Hubs and Tools](https://agu.confex.com/agu/agu24/prelim.cgi/Session/225615) session in the [google doc](https://docs.google.com/document/d/1RbuVA66X4Rl9MQhfYhZJh-RFFTM9uYGxtrox7KDwi8o/edit?usp=sharing) Julie made. Those interested in co-authoring, and presenting (I can't attend AGU this year), please take a look at the draft, add your name the author list and/or edit the abstract as needed. Looking for volunteers to submit it as well :). CC @jules32 @asteiker @betolink @andypbarrett @ateucher @danielfromearth @alexishunzinger

**Comment by asteiker** [comment]
I added an abstract draft in the shared doc for earthaccess, to submit to [IN043 - Showcasing your Earth Data Products, Tools, and Services](https://agu.confex.com/agu/agu24/prelim.cgi/Session/225163). I will also share in the [earthaccess discussion](https://github.com/nsidc/earthaccess/discussions/774)!

**Comment by jules32** [comment]
@eeholmes will submit an abstract about images -

[U001: Accelerating Scientific Discovery and Interdisciplinary Collaboration through Cloud Computing Hubs and Tools](https://agu.confex.com/agu/agu24/prelim.cgi/Session/225615) 
(A Barrett rec) Tasha Snow & Jessica Scheik

**Comment by jules32** [comment]
Hi All, Our abstract is ready for me to submit tomorrow (July 31)! Current co-authors are tagged below, and happy to add anyone else!

@ScienceCat18 @betolink @andypbarrett @amfriesz @asteiker @alexishunzinger @danielfromearth @michele-ornl @ateucher, Carl Boettiger, Eli Holmes, Yuvi Panda :)

**Comment by jules32** [comment]
I submitted 2 abstracts yesterday, and I know Amy Steiker did too, noted in 

https://docs.google.com/document/d/1RbuVA66X4Rl9MQhfYhZJh-RFFTM9uYGxtrox7KDwi8o/edit?usp=sharing. 

The abstract deadline has been extended to midnight ET today, then we'll close this issue.

We'll create a repo for planning like we did last year when we hear what was accepted

**Comment by ScienceCat18** [comment]
Thank you Julie for seeing this through! Much appreciated! 🙌 Sounds good about getting organized down the road.

**Comment by jules32** [comment]
Yay, thank you @ScienceCat18 for developing the Hub abstract!

**Comment by jules32** [comment]
I've added Peter Cornillion's (niversity of Rhode Island & 2022 Champion) abstract "Processing NASA Earth Science Data in the Amazon Web Services Cloud" to the doc

Closing this issue for now; we'll review/reopen as we hear back about sessions and start planning :)
