### ISSUE TITLE
Every Tues, 1pm ET Hackdays: Workshop Planning 

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/workshop-planning#35]
## Jan 16 agenda

- [x] walk through Bri's progress
- [x] review & merge open PRs and discuss progress
- [x] update group headers: Maybe "Next Month Upcoming" and "This Year Upcoming"?
- [x] Set Community Call dates

TODO: Summary of what we talked about after we met (recurring)

**Comment by stefaniebutland** [comment]
pull request: https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/pull/280

**Comment by stefaniebutland** [comment]
- want to know when Hackdays or tag ups are happening? look at the Roadmap Schedule view
- - thinking through how we'll use this repo. This is for planning and calendaring; the work of "doing" (prepping workshops) won't happen right here
- we set status names for issues as: This Week, This Quarter, This Year
  - manually change an issue's Status e.g. when you are working on a thing

**Comment by stefaniebutland** [comment]
### Jan 16 summary
Bri, Stef, Julie 

People want to be able to see ongoing NASA Openscapes and DAAC events, their planning status, and where they fit in our calendars. We've met twice now to cowork on populating a GitHub Project for this. Today we:
- walked through Bri's progress in adding issues, labels, dates, and Roadmap Schedule to our [MainPlanning GitHub Project](https://github.com/orgs/NASA-Openscapes/projects/7)
- reviewed & merged pull request to Cookbook explaining what this is and a bit of how to use it: [Cookbook: GitHub for Calendaring and Project Management](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/calendar-project-management.html)
- set Feb 20, 10 am PT / 1 pm ET for a Community Call: [“GitHub for NASA Openscapes community project management & calendaring - a work in progress" - Feb 20#50](https://github.com/NASA-Openscapes/how_we_work/issues/50) to share our specific use case and motivations (lightweight to welcome contributors, public to share "what's upcoming?") and to learn from audience how they do this

**Comment by jules32** [comment]
Next Coworking: 
- [ ] Would love to discuss & start drafting https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/issues/264

**Comment by jules32** [comment]
Closing this for now, to return to when we have regular workshop planning meetings again
