### ISSUE TITLE
ESDSWG - NASA Openscapes Talk - Mar 5-7

### ISSUE THREAD

**Issue by BriannaLind** [NASA-Openscapes/workshop-planning#38]
ESDSWG - Earth Science Data System Working Groups
March 5-7
Huntsville, AL

**Comment by BriannaLind** [comment]
@jules32 I'm going through last weeks notes and adding anything I can see :)

**Comment by jules32** [comment]
Meeting wiki page: https://wiki.earthdata.nasa.gov/display/ESDSWG

Attending: Julie

**Comment by jules32** [comment]
NASA Openscapes has 15 mins in the first morning to share about progress and vision: 

https://wiki.earthdata.nasa.gov/display/ESDSWG/2024+ESDSWG+Meeting+Agenda
