### ISSUE TITLE
Registration DUE 1/21/24 for AGU Chapman: Remote Sensing of the Water Cycle: Sensors to Science to Society and affiliated Workshops

### ISSUE THREAD

**Issue by ScienceCat18** [NASA-Openscapes/workshop-planning#54]

**Comment by stefaniebutland** [comment]
Workshop planning now in a separate issue: SWOT-PODAAC workshop AGU Chapman - Feb 13, 2024
[#2](https://github.com/NASA-Openscapes/workshop-planning/issues/2)

closing this issue
