### ISSUE TITLE
Submissions to AGU/CUAHSI's WaterSciCon due Jan 24

### ISSUE THREAD

**Issue by ScienceCat18** [NASA-Openscapes/workshop-planning#55]

**Comment by ScienceCat18** [comment]
Consider [submitting](https://agu.confex.com/agu/hydrology24/prelim.cgi/Home/0) to a PO.DAAC - USGS convened joint oral-workshop session at WaterSciCon:

LO-08 - **[Making Data More Accessible: Intersections of Terrestrial Hydrology Datasets](https://agu.confex.com/agu/hydrology24/prelim.cgi/Session/218465)** Catalina M Oaida Taglialatela, NASA Jet Propulsion Laboratory, California Institute of Technology, Pasadena, United States, Cassandra Nickles, Jet Propulsion Laboratory, California Institute of Technology, Pasadena, United States and Merritt Harlan, U.S. Geological Survey, Hydrologic Remote Sensing Branch, Lakewood CO, United States

Affiliated [workshop](https://acrobat.adobe.com/link/track?uri=urn%3Aaaid%3Ascds%3AUS%3A46cb7b02-6f1c-3716-bd37-9fe886c5d49d&viewer%21megaVerb=group-discover): Making Data More Accessible: Intersections of Terrestrial Hydrology Datasets - Workshop Edition Submitter: Cassandra Nickles, Jet Propulsion Laboratory, California Institute of Technology Learning Objectives:  Participants will learn about existing tools and services and form connections that help users navigate across different types of terrestrial hydrology observations (combinations of remote sensing, in situ, airborne, citizen science, etc.) Through hands-on demos and discussion, participants enabling data access will identify pain points and data access gaps common to the terrestrial hydrology community, supporting future progress for better data access for a variety of audiences. 

CC: @cassienickles co-convener

**Comment by stefaniebutland** [comment]
@ScienceCat18 Was a submission made? Or do we close this issue?
