### ISSUE TITLE
Earthdata Webinar: Cloud Cookbook - Feb 28

### ISSUE THREAD

**Issue by BriannaLind** [NASA-Openscapes/workshop-planning#60]
Date of Webinar: February 28 2024

**General Idea:**

1. Welcome to kinder open science & NASA Openscapes intro - Bri Lind, LP DAAC
3. Cookbook - Cassie Nickles, PO.DAAC
4. earthaccess & JupyterHub - Luis Lopez, NSIDC
5. How we teach workshops & closing - Alexis Hunzinger, GES DISC 

**Event prep:**
- tag up week of Feb. 5 
- dry run week of February 26

**Comment by BriannaLind** [comment]
@jules32 We need a Title and Description...... what do you think of **Kinder Science in the Cloud: Cloud Computing Resources from NASA Openscapes**? or maybe, **Community Developed Cloud Computing Resources: the Cloud Cookbook from NASA Openscapes**?

**Comment by jules32** [comment]
Great job on the abstract @BriannaLind 💯 💯 

**Title**: Community Developed Cloud Computing Resources: the Cloud Cookbook from NASA Openscapes
**Speakers**: Bri Lind, LP DAAC; Cassie Nickles, PO.DAAC; Luis Lopez, NSIDC; Alexis Hunzinger, GES DISC

**Short Description** (2 sentence description for newsletter):

[NASA Openscapes](https://nasa-openscapes.github.io/)  is a community of NASA data center staff and open science contributors who are supporting researchers migrating workflows to the Cloud.  Here we present the  [Earthdata Cloud Cookbook](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/): a compilation of open source tutorials, workflows, libraries, and cheatsheet that help people find, access, and apply NASA Earthdata. 

**Abstract** (should not exceed 150 words or so)

NASA Openscapes (https://nasa-openscapes.github.io/) is a community of NASA data center staff and open science contributors who are supporting researchers migrating workflows to the Cloud.  As part of this effort we are openly developing the Earthdata Cloud Cookbook: a compilation of open source tutorials, workflows, and cheatsheets that we have refined through teaching over 20 Cloud workshops with researchers using NASA Earthdata. We support NASA Earthdata users by developing an open science mindset focused on kindness and inclusion, as well as developing software to reduce time to science and meet researchers where they are. The earthaccess library and corn base image helps researchers access NASA Earthdata in a few lines of code – in Python, R, and MATLAB. We will share about this ongoing work and how we collaborate to share lessons learned and tackle challenges together - and welcome you to join the open science movement.

**Comment by BriannaLind** [comment]
I really like how we are using this!!! <3

**Comment by BriannaLind** [comment]
@jules32 I had a meeting with Jennifer today about the webinar and jotted down some notes:

- during event keep video off except for speaker - bandwidth is a challenge
- need to get bio/ photo for each of speakers
- do we have an invite list?/ email list..... is this actually a list from all of the DAACs?
- will need to make question list (might be interesting to compare answers to same cloud questions asked before
- start drafting ppt
- would be really cool to emphasize opportunity for discourse and contributions..... are we ready for that? 
- during co-working plan content and timing of dry run more specifically

**Comment by stefaniebutland** [comment]
source info for blog post  https://www.earthdata.nasa.gov/learn/webinars-and-tutorials/openscapes-2024-02-28

**Comment by jules32** [comment]
wonderful, thank you so much!

**Comment by BriannaLind** [comment]
Can we add/ do we already have a joint slidedeck going? @jules32 @betolink @alexishunzinger

**Comment by jules32** [comment]
@BriannaLind https://docs.google.com/presentation/d/1VbWZREJAPTVUPeVK0s8JC-yw-x3n2044qKZC1I6E34I/edit#slide=id.p

**Comment by BriannaLind** [comment]
Adjusted my slides!  I'm looking forward to dry run/ discussion tomorrow :)

**Comment by BriannaLind** [comment]
**Pre Event Polling Questions:**

1.  
2. How often do you work in cloud environments?
3. 
4. 
5. 

**Post Event Polling Questions:**
1. Do you find the content of the Cloud Cookbook useful?
2. What suggestions do you have for the Cloud Cookbook?
3. Are you comfortable contributing to the Cookbook? 
4.
5.

**Comment by BriannaLind** [comment]
Examples from Jennifer: 
**1.	Have you ever worked with data in the cloud?**
A.	Yes, frequently.
B.	Yes, a little.
C.	No, but I am interested.
D.	No, and I am currently not interested.

**4.	If you have used a Cloud platform in the past, which Cloud platform did you use?**
A.	Amazon Web Services
B.	Google Earth Engine
C.	Microsoft Azure
D.	None of the Above

**Comment by jules32** [comment]
Wooo great job on the Webinar everyone! That was really awesome, and so cool to see it come together over the last weeks. You are all so impressive and are making a huge difference :heart:

106 attendees! We'll post a blog next week and close this issue

**Comment by jules32** [comment]
Great job on this all! Blog post here (thank you @stefaniebutland !): https://nasa-openscapes.github.io/news/2024-03-12-nasa-earthdata-webinar/
