### ISSUE TITLE
ESDS Tech Spotlight - Feb 26

### ISSUE THREAD

**Issue by asteiker** [NASA-Openscapes/workshop-planning#62]
Date and time of Webinar: February 26 2024 from 11 - 12 MST / 1 - 2 EST

From https://wiki.earthdata.nasa.gov/display/ESDIS/Technology+Spotlight+Webinar+Series: 

**Overview**
The monthly ESDS Technology Spotlight webinars provide a platform for ESDIS, the DAACs, IMPACT, and other ESDS initiatives and competitive programs to showcase technology innovations to an ESDS-wide audience and to discuss how these technologies might be adapted and used throughout ESDS. The webinars are (generally) held on the 3rd Monday of the month and are open to everyone in the greater ESDS community.

**Guidelines**

Technology Spotlight Speaker Guidelines
Thanks for volunteering to share your technology as a Technology Spotlight talk. We’ve created
these guidelines to help you plan your presentation.
Talk length;
We’d like to leave time for discussion. The length of the talk will depend on how many talks are
planned for the session.
1 talk - 40 minutes
2 talks - 20 minutes each
Flash talks - 10 minutes each
Important points to cover:
Feel free to be creative with your talk. Storytelling and blue sky thinking are encouraged;
however, we’d like each speaker to cover the following basics:
1. What technology do you have?
2. What good is it? What is a use case (if applicable)?
3. How can other organizations within ESDS leverage it?
4. Next steps for those interested in the technology
Other logistics:
Please provide us with a title and short summary that we can share on the invite.
Technology Spotlight talks will be held via WebEx. You’ll be able to share your slides, but please
also provide them as a .pdf in case there are technical difficulties. After the talk, we will post
your slides on the Wiki.
Please provide contact information on your slides, and if possible, links to additional information

**Comment by asteiker** [comment]
Title ideas? How about this:

**earthaccess: Accelerating NASA Earthdata science through open, collaborative development**

**Comment by mfisher87** [comment]
Weak opinion: "science" -> "access"? While I agree the end result of faster/easier access is more productivity, "accelerating science" produces a less clear picture in my head than "accelerating access".

**Comment by BriannaLind** [comment]
@asteiker are you thinking a 20 or 40 minute talk?

LP can probably speak to how we use it in tutorials all the time......

idea: solicit user 'stories' from earthaccess github?

**Comment by betolink** [comment]
That's a great idea Bri! 

What about 

1. overview  - Amy/Matt? 
2. user story 1 -> earthaccess in action with EMIT/GEDI or some of the cool tutorials you guys are using it for at LP 
3. user story 2 -> Qiusheng's leafmap https://leafmap.org/notebooks/88_nasa_earth_data/ (I haven't asked  him but maybe he's available?)
4. user story 3 -> earthaccess in the cloud: Coiled/Dask workflow (James or one of us presenting)
5. Q/A 

I don't think I need to present anything unless Quisheng or James are not available. What do you all think?

**Comment by mfisher87** [comment]
>overview - Amy/Matt?

Happy to help out, but don't think I'll have the time to take the lead on that or work on it solo :)

What about a story or stories about our successes in outreach and engagement? For example, successes with labeling, being welcoming, engagement on social media, collaborations with other communities, inviting people to join the team, ... Thinking about where we are now, those strategies have really paid off! This could be an effective framing for some/all of our user success stories.

**Comment by betolink** [comment]
That's indeed very relevant, we could open the discussion/QA section with those points and briefly mention why we think this approach is working. Unfortunately we don't have all the time we need to cover all the cool aspects of the project. I'd say for the main block we focus on concrete examples of how this tool can reduce our "time to science".

**Comment by mfisher87** [comment]
>we could open the discussion/QA section with those points and briefly mention why we think this approach is working [...] I'd say for the main block we focus on concrete examples of how this tool can reduce our "time to science".

Agreed! What do you think about moving the brief discussion on community engagement and openness before the main block so it can be used as a framing device for the user stories you mentioned. For each of those, I can see ways that our community focus made those things possible, or at minimum much better than they would have otherwise been!

Our project's community focus is a theme that threads through everything rather than a "tack-on", which is I think the more common approach. I feel if we threaded this concept through the talk, we could more effectively communicate that without spending more time on it than we would if we talked abut it at the end. What do you think?

**Comment by BriannaLind** [comment]
@amfriesz  said he can speak to the utility of earthaccess if that is a help :)

**Comment by asteiker** [comment]
@mfisher87 @amfriesz @BriannaLind I started a [slide deck](https://docs.google.com/presentation/d/1K5RbQj4OKWt49kznIF9ct-cmWADlvdYA0eI7dA7_fFg/edit#slide=id.g6c52a2e8d8_0_177) based on everyone's feedback - thank you! I copied and added to the great intro deck from the gallery repo (https://nsidc.github.io/earthaccess-gallery/). Please feel free to contribute here. I also set up a time with @betolink and Qiusheng Tuesday Feb 20 at 9 MT to co-work on this presentation. Please let me know if you would like to join us!

**Comment by mfisher87** [comment]
That's going to be a heck of a day for me, but I think I can join you for up to an hour :) Would you mind sending an invite to me gmail address (this username @ gmail)?

**Comment by jules32** [comment]
Looking so great! I added a few comments and screenshots to the slide deck :)

**Comment by BriannaLind** [comment]
@jules32  this might be because it is internally oriented....... maybe @asteiker  has a special guest link :)

**Comment by Rapsodia86** [comment]
> I have the WebEx link in our calendar; please reply here if you'd like me to share it with you too.

Hi @jules32 ,
May I ask for the link? Thanks!

**Comment by jules32** [comment]
82 participants at 2:10ET!

**Comment by stefaniebutland** [comment]
When available, I'll edit the video to cut out discussion, and post to [NASA-Openscapes playlist](https://www.youtube.com/playlist?list=PLVVMU2rjWU7fP-iPS61EqxJCHf0I4WLTf) on Openscapes Youtube.

@giswqs do we have permission to include your section of the recording?

**Comment by stefaniebutland** [comment]
blog post published, links to recording and slides: [earthaccess: Accelerating NASA Earthdata access through open, collaborative development](https://nasa-openscapes.github.io/news/2024-03-04-earthaccess-tech-spotlight/). Also on [Openscapes blog](https://openscapes.org/blog/2024-03-04-earthaccess-tech-spotlight/)

@asteiker ok to close this issue?
