### ISSUE TITLE
Assemble Slidedeck for Methane Plume Webinar

### ISSUE THREAD

**Issue by BriannaLind** [NASA-Openscapes/workshop-planning#74]
Start putting slides together based on this outline! @akthorpe @kdchadwick @pgbrodrick @ebolch [use these shared slides](https://docs.google.com/presentation/d/1isDDIBi-RUSZQFaq7smHWXLBlmpuiEIBgY4WK-jvj_U/edit?usp=sharing)

[Agenda doc](https://docs.google.com/document/d/1OlVLLkHeSINvEr-CvLYbBw3RM3mIbY2ef3zrlhaiC28/edit)

1. **Rob/Andrew** (5 minutes): Introduce EMIT and Imaging spectroscopy
    - Instrument & GHG Center 
    - Coverage (orbit and targets) (VISIONS?)
    - Radiance and calibration
2. **Andrew** (15 minutes): How do we measure methane from space?
    - Atmospheric gas absorptions throughout the spectrum
    - Just talk about plume ratio (hard because radiance changes a lot)
    - Development with AVIRIS / GIFFs (how does it happen)
3. **Erik** (20 minutes): First notebook looking at radiance, highlighting the spectrum where we see methane, and then hard coded example 
4. **Andrew** (15 minutes): Interpretation (persistence, how do we think about it)
    - Orbital issues,
    - Coverage
    - clouds/mask generally 
    - Value of understanding persistence of large emissions 
    - Utility of enhancement identification vs. integrated understanding of total emissions 
5. **Erik** (30 minutes): Tutorial - time series visualization
6. **Andrew/Dana** (5 minutes): Wrap up
    - US GHG center for more context and resources

**Comment by BriannaLind** [comment]
I'm looking forward to our meeting coming up on Thursday - please add slides to the slide-deck linked above associated with the agenda...... btw, do we have specific locations that we want to use to show radiance @akthorpe ?

**Comment by akthorpe** [comment]
For the in and out of plume band ratios, you could first try scene emit20220815t042838.
Attached is a spreadsheet where I did this manually. The pixel locations are listed, so you should be able to replicate this.
Please let me know if you have any questions.

[In_Out_Plume_20220907a.xlsx](https://github.com/NASA-Openscapes/workshop-planning/files/14423245/In_Out_Plume_20220907a.xlsx)

**Comment by ebolch** [comment]
I couldn't reproduce that example. For some reason I was getting different pixel values at those downtrack and crosstrack locations. I thought maybe that example was from before the crosstrack was mirrored, which seemed to get me closer, but I still had to use some different pixels. I think this looks pretty good:

![image](https://github.com/NASA-Openscapes/workshop-planning/assets/34290812/3c42e3c8-f9e2-4d49-a451-0dad82bce2e8)

**Comment by akthorpe** [comment]
Thanks for sharing this, yes, I think this looks pretty good. Is it possible to have these plotted along with the ch4 target in one plot with different y axes? I think that could make things even more clear. In previous figures, I added vertical grey bars to emphasize agreement in bands with particularly strong features, like the attached example.

![Picture1](https://github.com/NASA-Openscapes/workshop-planning/assets/89597453/ff3d5f1d-7103-4790-aa3f-d098729b71d2)

**Comment by akthorpe** [comment]
I would like to upload a set of slides that I have been working on for the tutorial. Is the LP DAAC team able to grant me access to a Google Drive folder where I can upload these?

**Comment by ebolch** [comment]
Yeah I should be able to add the ch4 target in the same plot. As for the Google Drive space, we're using some provided by Openscapes,  @BriannaLind should be able to add you.

**Comment by BriannaLind** [comment]
@akthorpe you should be good to go now!  Let me know if its not working

**Comment by akthorpe** [comment]
@BriannaLind 
I was able to upload the full draft presentation with the videos, but it is very large and can't be viewed using Google Slides:
https://drive.google.com/drive/folders/19T-PmknqriGB_IXFky0rudbIWZ_oZwLh?usp=sharing

I also added a version without the videos that can be viewed with Google Slides.

@kdchadwick 
It would be great if you could do a pass and help me refine this content.

**Comment by akthorpe** [comment]
@ebolch The JPL team had a conversation with a colleague who has been exploring the in/out of plume ratios. She was able to generate nice examples by matching reflectance spectra from in and out of methane plumes. One example of two matched spectra is attached here. This resulted in a nice fit, similar to what I have attached. Are you able to see if this approach results in an improved result?

<img width="488" alt="Screenshot 2024-03-08 at 9 52 16 AM" src="https://github.com/NASA-Openscapes/workshop-planning/assets/89597453/9ead996f-6110-4b41-99b7-ba823f115090">
<img width="435" alt="Screenshot 2024-03-08 at 9 50 15 AM" src="https://github.com/NASA-Openscapes/workshop-planning/assets/89597453/4d8244f1-4afc-4fec-8de2-0ea74fa4a59e">

@pgbrodrick Could you please share with Erik a recent methane matched filter target spectrum? The example I shared previously was from the early days of the EMIT mission.
