### ISSUE TITLE
Add attendees to Github/ coordinate list with Openscapes

### ISSUE THREAD

**Issue by BriannaLind** [NASA-Openscapes/workshop-planning#76]
need to add roughly ~200 participants to 'workshop team' for [EMIT Methane Webinar ](https://github.com/NASA-Openscapes/workshop-planning/issues/9)

**Comment by BriannaLind** [comment]
@jules32 @stefaniebutland could you guys help me with this sometime next week?

**Comment by stefaniebutland** [comment]
Can do @BriannaLind ! If you have the list of users' GitHub names I'd be happy to screenshare while semi-automatically adding them to the workshop team using the kyber R package. 30-min zoom should be plenty. I'll DM you a link to my calendar to book time

**Comment by stefaniebutland** [comment]
meeting 09:30am Fri, 8 Mar 2024

**Comment by BriannaLind** [comment]
Hey Steph!  This is the message I got from your scheuler...... what time zone are you actually in? 
![image](https://github.com/NASA-Openscapes/workshop-planning/assets/104585874/3b11e166-8c3c-4e28-ab49-5c42c030f9b1)

**Comment by stefaniebutland** [comment]
I'm on Pacific; it shows correctly in my calendar for me AND in your timezone for you! 🥳 


<img width="471" alt="Screenshot 2024-02-29 at 6 48 18 AM" src="https://github.com/NASA-Openscapes/workshop-planning/assets/11927811/59ca247f-553e-4f28-98b1-48202df006e8">

**Comment by BriannaLind** [comment]
can you share the link to this meeting?  It is not showing up on my calendar

**Comment by stefaniebutland** [comment]
DM'd

**Comment by stefaniebutland** [comment]
@BriannaLind do workshop participants already have the google form link to get 2i2c access? Can you pls click on it to ensure it's the current one, not one that says "deprecated ....replaced by this form ..."

I want to make sure we're not putting up a barrier

**Comment by BriannaLind** [comment]
@stefaniebutland Im not sure what you mean, We have a sign up for the workshop on a separate google doc, I was going to pull the names and github for that

**Comment by stefaniebutland** [comment]
ok, that totally works @BriannaLind !
