### ISSUE TITLE
Share IME/flux equation with Erik to incorporate in tutorial

### ISSUE THREAD

**Issue by BriannaLind** [NASA-Openscapes/workshop-planning#79]
There is expert knowledge from @akthorpe needed to incorporate this into the tutorial, please share info/code with @ebolch so can be done in advance of Feb. 29

**Comment by akthorpe** [comment]
@ebolch Attached is a slide that lays out the IME calculation. please let me know if you have any questions.
[20230221a_Thorpe_IME.pptx](https://github.com/NASA-Openscapes/workshop-planning/files/14364529/20230221a_Thorpe_IME.pptx)
